"""empty message

Revision ID: f15fff2d268a
Revises: d5510282144a
Create Date: 2016-03-30 12:17:06.902395

"""

# revision identifiers, used by Alembic.
revision = 'f15fff2d268a'
down_revision = 'd5510282144a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.add_column(u'users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column(u'users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column(u'users', sa.Column('location', sa.String(length=64), nullable=True))
    op.add_column(u'users', sa.Column('member_me', sa.DateTime(), nullable=True))
    op.add_column(u'users', sa.Column('name', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'users', 'name')
    op.drop_column(u'users', 'member_me')
    op.drop_column(u'users', 'location')
    op.drop_column(u'users', 'last_seen')
    op.drop_column(u'users', 'about_me')
    op.drop_table('follows')
    ### end Alembic commands ###
