# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 02:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=datetime.datetime(2016, 3, 22, 2, 9, 51, 437349, tzinfo=utc), max_length=300),
            preserve_default=False,
        ),
    ]
