# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 11:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160322_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 23, 11, 15, 2, 513074, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
