# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 11:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160323_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.CharField(default=datetime.datetime(2016, 3, 23, 11, 27, 34, 35880, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
    ]
